package net.hubalek.android.gaugebattwidget.themes.ics;

import net.hubalek.android.gaugebattwidget.themes.library.AbstractStatusBarNotificationService;

/**
 * Notification Service.
 */
public class Service extends AbstractStatusBarNotificationService {

    private static final int[] STATUS_ICONS = {
            R.drawable.battery_status_0,
            R.drawable.battery_status_1,
            R.drawable.battery_status_2,
            R.drawable.battery_status_3,
            R.drawable.battery_status_4,
            R.drawable.battery_status_5,
            R.drawable.battery_status_6,
            R.drawable.battery_status_7,
            R.drawable.battery_status_8,
            R.drawable.battery_status_9,
            R.drawable.battery_status_10,
            R.drawable.battery_status_11,
            R.drawable.battery_status_12,
            R.drawable.battery_status_13,
            R.drawable.battery_status_14,
            R.drawable.battery_status_15,
            R.drawable.battery_status_16,
            R.drawable.battery_status_17,
            R.drawable.battery_status_18,
            R.drawable.battery_status_19,
            R.drawable.battery_status_20,
            R.drawable.battery_status_21,
            R.drawable.battery_status_22,
            R.drawable.battery_status_23,
            R.drawable.battery_status_24,
            R.drawable.battery_status_25,
            R.drawable.battery_status_26,
            R.drawable.battery_status_27,
            R.drawable.battery_status_28,
            R.drawable.battery_status_29,
            R.drawable.battery_status_30,
            R.drawable.battery_status_31,
            R.drawable.battery_status_32,
            R.drawable.battery_status_33,
            R.drawable.battery_status_34,
            R.drawable.battery_status_35,
            R.drawable.battery_status_36,
            R.drawable.battery_status_37,
            R.drawable.battery_status_38,
            R.drawable.battery_status_39,
            R.drawable.battery_status_40,
            R.drawable.battery_status_41,
            R.drawable.battery_status_42,
            R.drawable.battery_status_43,
            R.drawable.battery_status_44,
            R.drawable.battery_status_45,
            R.drawable.battery_status_46,
            R.drawable.battery_status_47,
            R.drawable.battery_status_48,
            R.drawable.battery_status_49,
            R.drawable.battery_status_50,
            R.drawable.battery_status_51,
            R.drawable.battery_status_52,
            R.drawable.battery_status_53,
            R.drawable.battery_status_54,
            R.drawable.battery_status_55,
            R.drawable.battery_status_56,
            R.drawable.battery_status_57,
            R.drawable.battery_status_58,
            R.drawable.battery_status_59,
            R.drawable.battery_status_60,
            R.drawable.battery_status_61,
            R.drawable.battery_status_62,
            R.drawable.battery_status_63,
            R.drawable.battery_status_64,
            R.drawable.battery_status_65,
            R.drawable.battery_status_66,
            R.drawable.battery_status_67,
            R.drawable.battery_status_68,
            R.drawable.battery_status_69,
            R.drawable.battery_status_70,
            R.drawable.battery_status_71,
            R.drawable.battery_status_72,
            R.drawable.battery_status_73,
            R.drawable.battery_status_74,
            R.drawable.battery_status_75,
            R.drawable.battery_status_76,
            R.drawable.battery_status_77,
            R.drawable.battery_status_78,
            R.drawable.battery_status_79,
            R.drawable.battery_status_80,
            R.drawable.battery_status_81,
            R.drawable.battery_status_82,
            R.drawable.battery_status_83,
            R.drawable.battery_status_84,
            R.drawable.battery_status_85,
            R.drawable.battery_status_86,
            R.drawable.battery_status_87,
            R.drawable.battery_status_88,
            R.drawable.battery_status_89,
            R.drawable.battery_status_90,
            R.drawable.battery_status_91,
            R.drawable.battery_status_92,
            R.drawable.battery_status_93,
            R.drawable.battery_status_94,
            R.drawable.battery_status_95,
            R.drawable.battery_status_96,
            R.drawable.battery_status_97,
            R.drawable.battery_status_98,
            R.drawable.battery_status_99,
            R.drawable.battery_status_100,
    };

    @Override
    protected int[] getStatusBarIconsArray() {
        return STATUS_ICONS;
    }
}
